apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  SA_PASSWORD: "SimplePassword_123"
  CONNECTION_STRING: "Server=db-service;Database=MaterialBalanceDB;User Id=sa;Password=SimplePassword_123;TrustServerCertificate=True;"